server:
  port: 8095
spring:
  application:
    name: server-file
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - localhost:22122
  pool:
    max-total: -1
    max-wait-millis: 5000
    max-total-per-key: 50
    max-idle-per-key: 10
    max_idle_per_key: 5