server:
    port: 8096

spring:
    application:
        name: server-workflow
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/xbase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
