server:
  port: 8090
  servlet:
    context-path:

spring:
  application:
    name: base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: server-uac
          uri: lb://server-uac
          predicates:
            - Path=/uac/**
          filters:
            - StripPrefix=1
        - id: base-auth
          uri: lb://base-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: server-message
          uri: lb://server-message
          predicates:
            - Path=/msg/**
          filters:
            - StripPrefix=1
        - id: base-admin
          uri: lb://base-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
